spring:
  application:
    name: bilibili
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bilibili_course?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password:
server:
  port: 8183
  servlet:
    context-path: /courses


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.example.DTO
  map-underscore-to-camel-case: true